// <auto-generated />
using Borderlands2Guns.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Borderlands2Guns.Migrations
{
    [DbContext(typeof(Borderlands2GunsContext))]
    partial class Borderlands2GunsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Borderlands2Guns.Models.Guns", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("Accuracy");

                    b.Property<int>("AllTypesDamageOnTargetRank");

                    b.Property<int>("AllTypesElementalDamageOnTargetRank");

                    b.Property<int>("Brand");

                    b.Property<decimal>("Chance");

                    b.Property<int>("Damage");

                    b.Property<decimal>("DamageOnTarget");

                    b.Property<decimal>("DamageTimesFireRate");

                    b.Property<decimal>("DamageTimesFireRateTimesMagazineSize");

                    b.Property<decimal>("DamageTimesFireRateTimesMagazineSizePerReloadSpeed");

                    b.Property<int>("EachElementalTypeDamageOnTargetRank");

                    b.Property<int>("EachTypeDamageOnTargetRank");

                    b.Property<decimal>("ElementalDamageOnTargetTimesDamagePerSecondTimesChance");

                    b.Property<decimal>("ElementalDamagePerSecond");

                    b.Property<decimal>("ElementalDamagePerSecondTimesChance");

                    b.Property<int?>("ElementalEffect");

                    b.Property<decimal>("FireRate");

                    b.Property<int>("Level");

                    b.Property<int>("MagazineSize");

                    b.Property<string>("Name");

                    b.Property<decimal>("ReloadSpeed");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.ToTable("Guns");
                });
#pragma warning restore 612, 618
        }
    }
}
